# Generated by Django 4.2.6 on 2023-10-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biusvelim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='categorias',
            field=models.CharField(choices=[('R', 'ROMANTICA'), ('D', 'DRAMA'), ('C', 'COMEDIA'), ('A', 'ACCION')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='edad_limite',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Niños', 'Niños')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idioma',
            field=models.CharField(choices=[('ES', 'ESPAÑOL'), ('EN', 'INGLES')], max_length=2),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='edad_limite',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Niños', 'Niños')], max_length=10),
        ),
    ]
